// Code generated by go generate gen_inflate.go. DO NOT EDIT.

package flate

import (
	"bytes"
	"fmt"
	"io"
	"math/bits"
)

// huffmanBytesReaderFast decodes one Huffman block from `*bytes.Reader` without
// per-byte `ReadByte` calls. It snapshots the backing slice and byte index,
// advances a local index while decoding, then writes the index back before
// return and clears `prevRune` after any byte read.
func (f *decompressor) huffmanBytesReaderFast() {
	const (
		stateInit = iota // Zero value must be stateInit
		stateDict
	)
	fr := f.r.(*bytes.Reader)
	frState := bytesReaderStateOf(fr)
	frBuf := frState.s
	frPos := frState.i
	frRead := false
	roffset := f.roffset

	// Keep the bit buffer and dictionary in locals for the hot loop. The
	// decoder writes b and nb back to f before each return.
	fnb, fb, dict := f.nb, f.b, &f.dict

	switch f.stepState {
	case stateInit:
		goto readLiteral
	case stateDict:
		goto copyHistory
	}

readLiteral:
	// Read literal and/or (length, distance) according to RFC section 3.2.3.
	{
		var v int
		{
			// Inlined v, err := f.huffSym(f.hl)
			// A chunk count of zero marks an invalid Huffman sequence.
			n := uint(f.hl.maxRead)
			for {
				for fnb < n {
					if frPos >= int64(len(frBuf)) {
						frRead = true
						f.b, f.nb = fb, fnb
						f.err = io.ErrUnexpectedEOF
						goto saveReturn
					}
					c := frBuf[frPos]
					frPos++
					frRead = true
					roffset++
					fb |= uint32(c) << (fnb & regSizeMaskUint32)
					fnb += 8
				}
				chunk := f.hl.chunks[fb&(huffmanNumChunks-1)]
				n = uint(chunk & huffmanCountMask)
				if n > huffmanChunkBits {
					chunk = f.hl.links[chunk>>huffmanValueShift][(fb>>huffmanChunkBits)&f.hl.linkMask]
					n = uint(chunk & huffmanCountMask)
				}
				if n <= fnb {
					if n == 0 {
						f.b, f.nb = fb, fnb
						if debugDecode {
							fmt.Println("huffsym: n==0")
						}
						f.err = CorruptInputError(roffset)
						goto saveReturn
					}
					fb = fb >> (n & regSizeMaskUint32)
					fnb = fnb - n
					v = int(chunk >> huffmanValueShift)
					break
				}
			}
		}

		var length int
		switch {
		case v < 256:
			dict.writeByte(byte(v))
			if dict.availWrite() == 0 {
				f.toRead = dict.readFlush()
				// huffmanBytesReader is the shared resume step for
				// `*bytes.Reader` blocks; doStep decides which decoder
				// handles it. Both decoders share the same suspended
				// state (b/nb/roffset/dict/reader index), so either can
				// resume this block.
				f.step = huffmanBytesReader
				f.stepState = stateInit
				f.b, f.nb = fb, fnb
				goto saveReturn
			}
			goto readLiteral
		case v == 256:
			f.b, f.nb = fb, fnb
			f.roffset = roffset
			frState.i = frPos
			if frRead {
				// See saveReturn: any byte read clears `prevRune`.
				frState.prevRune = -1
			}
			f.finishBlock()
			return
		// otherwise, reference to older data
		case v < 265:
			length = v - (257 - 3)
		case v < maxNumLit:
			val := decCodeToLen[(v - 257)]
			length = int(val.length) + 3
			n := uint(val.extra)
			for fnb < n {
				if frPos >= int64(len(frBuf)) {
					frRead = true
					f.b, f.nb = fb, fnb
					if debugDecode {
						fmt.Println("morebits n>0:", io.EOF)
					}
					f.err = io.EOF
					goto saveReturn
				}
				c := frBuf[frPos]
				frPos++
				frRead = true
				roffset++
				fb |= uint32(c) << (fnb & regSizeMaskUint32)
				fnb += 8
			}
			length += int(fb & bitMask32[n])
			fb >>= n & regSizeMaskUint32
			fnb -= n
		default:
			if debugDecode {
				fmt.Println(v, ">= maxNumLit")
			}
			f.err = CorruptInputError(roffset)
			f.b, f.nb = fb, fnb
			goto saveReturn
		}

		var dist uint32
		if f.hd == nil {
			for fnb < 5 {
				if frPos >= int64(len(frBuf)) {
					frRead = true
					f.b, f.nb = fb, fnb
					if debugDecode {
						fmt.Println("morebits f.nb<5:", io.EOF)
					}
					f.err = io.EOF
					goto saveReturn
				}
				c := frBuf[frPos]
				frPos++
				frRead = true
				roffset++
				fb |= uint32(c) << (fnb & regSizeMaskUint32)
				fnb += 8
			}
			dist = uint32(bits.Reverse8(uint8(fb & 0x1F << 3)))
			fb >>= 5
			fnb -= 5
		} else {
			// A chunk count of zero marks an invalid Huffman sequence.
			n := uint(f.hd.maxRead)
			for {
				for fnb < n {
					if frPos >= int64(len(frBuf)) {
						frRead = true
						f.b, f.nb = fb, fnb
						f.err = io.ErrUnexpectedEOF
						goto saveReturn
					}
					c := frBuf[frPos]
					frPos++
					frRead = true
					roffset++
					fb |= uint32(c) << (fnb & regSizeMaskUint32)
					fnb += 8
				}
				chunk := f.hd.chunks[fb&(huffmanNumChunks-1)]
				n = uint(chunk & huffmanCountMask)
				if n > huffmanChunkBits {
					chunk = f.hd.links[chunk>>huffmanValueShift][(fb>>huffmanChunkBits)&f.hd.linkMask]
					n = uint(chunk & huffmanCountMask)
				}
				if n <= fnb {
					if n == 0 {
						f.b, f.nb = fb, fnb
						if debugDecode {
							fmt.Println("huffsym: n==0")
						}
						f.err = CorruptInputError(roffset)
						goto saveReturn
					}
					fb = fb >> (n & regSizeMaskUint32)
					fnb = fnb - n
					dist = uint32(chunk >> huffmanValueShift)
					break
				}
			}
		}

		switch {
		case dist < 4:
			dist++
		case dist < maxNumDist:
			nb := uint(dist-2) >> 1
			// have 1 bit in bottom of dist, need nb more.
			extra := (dist & 1) << (nb & regSizeMaskUint32)
			for fnb < nb {
				if frPos >= int64(len(frBuf)) {
					frRead = true
					f.b, f.nb = fb, fnb
					if debugDecode {
						fmt.Println("morebits f.nb<nb:", io.EOF)
					}
					f.err = io.EOF
					goto saveReturn
				}
				c := frBuf[frPos]
				frPos++
				frRead = true
				roffset++
				fb |= uint32(c) << (fnb & regSizeMaskUint32)
				fnb += 8
			}
			extra |= fb & bitMask32[nb]
			fb >>= nb & regSizeMaskUint32
			fnb -= nb
			dist = 1<<((nb+1)&regSizeMaskUint32) + 1 + extra
			// slower: dist = bitMask32[nb+1] + 2 + extra
		default:
			f.b, f.nb = fb, fnb
			if debugDecode {
				fmt.Println("dist too big:", dist, maxNumDist)
			}
			f.err = CorruptInputError(roffset)
			goto saveReturn
		}

		// No check on length; encoding can be prescient.
		if dist > uint32(dict.histSize()) {
			f.b, f.nb = fb, fnb
			if debugDecode {
				fmt.Println("dist > dict.histSize():", dist, dict.histSize())
			}
			f.err = CorruptInputError(roffset)
			goto saveReturn
		}

		f.copyLen, f.copyDist = length, int(dist)
		goto copyHistory
	}

copyHistory:
	// Perform a backwards copy according to RFC section 3.2.3.
	{
		cnt := dict.tryWriteCopy(f.copyDist, f.copyLen)
		if cnt == 0 {
			cnt = dict.writeCopy(f.copyDist, f.copyLen)
		}
		f.copyLen -= cnt

		if dict.availWrite() == 0 || f.copyLen > 0 {
			f.toRead = dict.readFlush()
			// See the readLiteral flush above: shared resume step for
			// `*bytes.Reader` blocks, routed by doStep.
			f.step = huffmanBytesReader // We need to continue this work
			f.stepState = stateDict
			f.b, f.nb = fb, fnb
			goto saveReturn
		}
		goto readLiteral
	}

saveReturn:
	f.roffset = roffset
	frState.i = frPos
	if frRead {
		// Match `bytes.Reader.ReadByte`, which invalidates `UnreadRune`
		// before checking for EOF: any read attempt, successful or not,
		// clears `prevRune`.
		frState.prevRune = -1
	}
}
